# 1. 정적 or 동적

# mode = "static"        # 정적 (프로토타입용): 외부 Cloud에서 KAIST 내부로 접근이 불가하여, 임시로 데이터를 같이 Push 하는 방식 
mode = "dynamic"     # 동적 (실제 적용): Cloud에서 외부 DB로 접근하여 현재 시간 기준으로 실시간 표출

# 2. 정적일 경우, 분석 기준 시간을 고정
current_time_test = "2026-01-29 14:32"

# 3. KAKAO Map API key
kakao_api_key = "fc1c450fc44c5cda47534a556fe9b4f2"   # 현재 백정엽 KAKAO 계정 API key. 교체 후 (https://developers.kakao.com/) 에서 Web 사이트 도메인 등록 필수.

# 4. 비교 분석할 기간 default setting
previous_days = 7

# 5. 임의 설정 값들 (Page3. 서비스 접근성 tab에 해당)

service_population = 18642
ODD_population = 12468
service_area = 2154953
ODD_area = 1654749

total_people_count = 300 # 총 사람 수
total_diabled_count = 90 # 장애인 수
total_olderadults_count = 210 # 고령자 수

# 6. Path들 정의 (나중에 수정&추가 할 각종 파일들 위치 기록해두었습니다.)
sejong_Station = 'data/ODD/vulnerable/Station_Vulnerable.shp'                        # 교통약자 지역 - 세종 Station 정보
daejeon_Station = 'data/ODD/convenience/Station_Convenience.shp'                      # 교통소외 지역 - 대전 Station 정보

Population = 'data/population/Population_Sample_Revised.shp'    # 100m 그리드별 주거 인구수 데이터


# 7. "동적"일 경우, 접속할 DB 선택

# [database]   # AI x mobility 자체 구축 DB, 접속은 가능하지만, 데이터는 없음.
# user = "kaist_db"
# passwd = "kaist502507"
# host = "20.41.122.158"
# port = 3306
# db = "kaist_db"
# charset = "utf8mb4"
# use_unicode = true

# [database]         # Health design Lab 자체 구축 DB, 장기간 데이터 쌓여 있음 (프로토타입용)
# user = "root"
# passwd = "3644"
# host = "143.248.121.90"
# port = 3306
# db = "hdl"
# charset = "utf8mb4"
# use_unicode = true

[database]         # nzero DB
user = "k-10-kaist-mariadb"
passwd = "4ddd94cb24e15272b9db8a6511eec6e9"
host = "4.217.187.173"
port = 30000
db = "kaist"
charset = "utf8mb4"
use_unicode = true


# 6. 교통약자지역, 교통소외지역 정의

[vulnerable_area] # 교통약자지역
region = "vulnerable_area"      # 현재 세종으로 세팅
lat = 37.215843
lng = 126.819740
level = 6

[underserved_area] # 교통소외지역
region = "underserved_area"      # 현재 대전으로 세팅
lat = 37.215843
lng = 126.819740
level = 6
